name: Build

on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'

            - name: Build with Maven
              run: mvn test
            
            - name: Setup Maven
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
                USERNAME: JeffreyRiggle
              run: |
                envsubst < settings.tmpl > ~/.m2/settings.xml
            
            - name: Version Bump
              if: startsWith(github.event.head_commit.message, 'Auto Version') != true
              run: |
                read_dom() {
                  IFS=\>
                  read -d \< ENTITY CONTENT
                }

                version=""

                while read_dom; do
                    if [[ $ENTITY = "version" ]]; then
                        version=$CONTENT
                        break
                    fi
                done < pom.xml

                IFS='.' read -r -a sections <<< "$version"
                patchVersion="${sections[2]}"
                newPatchVersion="$(($patchVersion + 1))"
                newVersion="${sections[0]}.${sections[1]}.${newPatchVersion}"
                contents=`cat pom.xml`
                echo "${contents//<version>$version</<version>$newVersion<}" > pom.xml
                
                git config --local user.email "$(git log --format='%ae' HEAD^!)"
                git config --local user.name "$(git log --format='%an' HEAD^!)"
                git add pom.xml
                git commit -m "Auto Version"
                git push

            - name: Deploy
              if: startsWith(github.event.head_commit.message, 'Auto Version') != true
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
              run: |
                mvn deploy